name: C/C++ CI

on:
  watch:
    types: [started]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check

